### ISSUE TITLE
error 500: "TypeError: Cannot read property 'resumption' of undefined" when authenticating with Facebook

### ISSUE THREAD

**Issue by hofman-p** [mattdot/botauth#14]
Hello,

I am currently able talk with my bot using Microsoft Bot Framework (Webapp & Messenger), it works, with different dialogs etc. I use ngrok endpoint on my Dev Messenger app and Microsoft Bot Framework bot. On my webapp (without bot), I implemented passport-facebook authentification to my MongoDB and it works well, I can connect choosing between local or Facebook authentication, and get back data.

What I want is now is one of these solutions:

1. From the bot client, my users have to login using Facebook channel (or locally on my webapp, using bot <iframe> webapp channel, or on localhost test with ngrok...) to my remote API, so with the bot I can get back some data from my MongoDB, as I do on my webapp. I need at least my Facebook ID.

2. Connect transparently to my remote API with Facebook authentication, so when users talk, they are directly connected, no webapp modal or anything, I can directly use their information from my remote MongoDB, and let's go.

I tried to implement 1) solution, because I really don't know how to do the second solution, which would be amazing for users.

But when I try to authenticate with Facebook using botauth, I have this error on:

```
TypeError: Cannot read property 'resumption' of undefined
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/botauth/lib/index.js:156:56
    at Layer.handle [as handle_request] (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/express/lib/router/route.js:137:13)
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/botauth/lib/resumption.js:35:13
    at Layer.handle [as handle_request] (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/express/lib/router/route.js:137:13)
    at complete (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/middleware/authenticate.js:250:13)
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/middleware/authenticate.js:257:15
    at pass (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/authenticator.js:421:14)
    at Authenticator.transformAuthInfo (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/authenticator.js:443:5)
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/middleware/authenticate.js:254:22
    at IncomingMessage.req.login.req.logIn (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/http/request.js:63:13)
    at Strategy.strategy.success (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport/lib/middleware/authenticate.js:235:13)
    at verified (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport-oauth2/lib/strategy.js:177:20)
    at Strategy.FacebookStrategy [as _verify] (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/app.js:82:12)
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport-oauth2/lib/strategy.js:193:24
    at /Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/passport-facebook/lib/strategy.js:181:5
    at passBackControl (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/Users/pierre/Desktop/Work/GitHub/alenvi-bot/node_modules/oauth/lib/oauth2.js:157:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

(picture here: https://puu.sh/vQPNb/917c710ff8.png )

I nearly copy / pasted your Facebook example, just removing Luis, and using Express instead of Restify.
I start by saying 'profile', then I click on 'connect', and then I have the error I described above. I have to cancel after.
(picture: https://puu.sh/vQQ7A/1a37693288.png)

Here is a bit of code:

```
var ba = new botauth.BotAuthenticator(app, bot, {
  baseUrl: "https://" + WEBSITE_HOSTNAME, secret: BOTAUTH_SECRET
}).provider("facebook", (options) => {
  return new FacebookStrategy({
    clientID: process.env.FACEBOOK_APP_ID || FACEBOOK_APP_ID,
    clientSecret: process.env.FACEBOOK_APP_SECRET || FACEBOOK_APP_SECRET,
    callbackURL: options.callbackURL,
    profileFields: ['id', 'emails', 'name', 'photos']
  }, (accessToken, refreshToken, profile, done) => {
    profile.accessToken = accessToken;
    profile.refreshToken = refreshToken;
    console.log(profile);
    return done(null, profile);
  });
});
```
` console.log(profile);` code displays well all what I need in my console. So it seems to nearly work ! 

But:
```
bot.dialog("/profile", [].concat(
  ba.authenticate("facebook"),
  function(session, results) {
    //get the facebook profile
    var user = ba.profile(session, "facebook");
    //var user = results.response;
    console.log(user);
    console.log("hello");
  }
));
```
`console.log(user);` and `console.log("hello");` don't log anything (because it's in response of the callback I suppose)

Can you help me ? I feel really lost, after an entire day on this.

Do not hesitate to tell me if you need something more.

Thank you,

Pierre

**Comment by hofman-p** [comment]
Okay I resolved it using the same code, but with Restify instead of Express.
I really don't know what happened !

Also, you should add to locale/ sentences like 'cancel', 'try again', and your sentence concerning the magic number, because I'm currently modifying it directly in your sources.

Anyway, thanks !

**Comment by mattdot** [comment]
if you provide a botauth.json file you can override the default messages ... see the Dropbox sample which does this https://github.com/MicrosoftDX/botauth/blob/master/examples/dropbox/locale/en/botauth.json you can also completely override the magic code page with your own html page by setting successRedirect option.  see the Evernote sample which does this https://github.com/MicrosoftDX/botauth/tree/master/examples/evernote

**Comment by hofman-p** [comment]
Yes I already use botauth.json to override some default messages, but I don't know how to do it for dialogs like 'cancel' for example, so I did it in your source.
I'll try to override magic code page so.
Thank you for your reply !
