### ISSUE TITLE
TypeError: Cannot read property 'resumption' of undefined

### ISSUE THREAD

**Issue by nsantini** [mattdot/botauth#16]
After logging in into Facebook and getting redirected I get this error:

TypeError: Cannot read property 'resumption' of undefined
    at node_modules/botauth/lib/index.js:156:56
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at node_modules/botauth/lib/resumption.js:35:13
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:137:13)
    at complete (node_modules/passport/lib/middleware/authenticate.js:250:13)
    at node_modules/passport/lib/middleware/authenticate.js:257:15
    at pass (node_modules/passport/lib/authenticator.js:421:14)
    at Authenticator.transformAuthInfo (node_modules/passport/lib/authenticator.js:443:5)

**Comment by hofman-p** [comment]
If that can help you, I had this error too (https://github.com/MicrosoftDX/botauth/issues/14), I resolved it using Restify instead of Express.
Maybe it'll solve your problem.

Would be nice if botauth works with Express ! :)

**Comment by nsantini** [comment]
thanks @hofman-p , that was my thought too. Unfortunately for me I can't replace express with restify, I need dynamic routing and restify hasn't played along well for that

would be good to understand how big the job to make it work with express would be...

closing this now
